# Generated by Django 4.1.7 on 2024-10-27 01:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0003_alter_usertoken_token_alter_usertoken_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserToken',
        ),
    ]
