# Generated by Django 4.1.7 on 2024-11-02 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_message_message_type_message_user_embeddingdocument_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LanguageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('display_name', models.CharField(max_length=255)),
                ('max_tokens', models.IntegerField()),
                ('max_prompt_tokens', models.IntegerField()),
                ('max_response_tokens', models.IntegerField()),
                ('frequency_penalty', models.FloatField(default=0.0)),
                ('presence_penalty', models.FloatField(default=0.0)),
                ('temperature', models.FloatField(default=0.7)),
                ('top_p', models.FloatField(default=1.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
