# Generated by Django 4.1.7 on 2024-11-17 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0009_languagemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='languagemodel',
            name='image_support',
            field=models.BooleanField(default=False),
        ),
    ]
